// ============================================================================
// Riftbound TCG — Origins Set: Card Index
// ============================================================================
// Auto-generated. Re-run tools/generate-cards.mjs to update.
// Combines curated sample cards with generated cards for the full set.
// ============================================================================

import { type CardDefinition } from "../../models/card.js";

// Curated sample cards (22 cards with hand-crafted abilities and scripts)
export { originsCards as sampleCards } from "./sample-cards.js";
import { originsCards as sampleCards } from "./sample-cards.js";

export { kaisaDaughterOfTheVoidLegend, volibearRelentlessStormLegend, dariusHandOfNoxusLegend, ahriNineTailedFoxLegend, yasuoUnforgivenLegend, leonaRadiantDawnLegend, teemoSwiftScoutLegend, missFortuneBountyHunterLegend, settTheBossLegend } from "./legends.js";
export { dariusTrifarianChampion, dravenShowboatChampion, tryndamereBarbarianChampion, vayneHunterChampion, viDestructiveChampion, kaisaSurvivorChampion, volibearFuriousChampion, ahriAlluringChampion, blitzcrankImpassiveChampion, sonaHarmoniousChampion, taricProtectorChampion, yasuoRemorsefulChampion, leeSinAsceticChampion, leonaZealotChampion, drMundoExpertChampion, ekkoRecurrentChampion, heimerdingerInventorChampion, kaisaEvolutionaryChampion, malzaharFanaticChampion, viktorInnovatorChampion, ahriInquisitiveChampion, teemoStrategistChampion, aniviaPrimalChampion, leeSinCenteredChampion, qiyanaVictoriousChampion, udyrWildmanChampion, volibearImposingChampion, warwickHunterChampion, missFortuneCaptainChampion, settBrawlerChampion, kaynUnleashedChampion, kogmawCausticChampion, missFortuneBuccaneerChampion, nocturneHorrifyingChampion, teemoScoutChampion, twistedFateGamblerChampion, jinxRebelChampion, yasuoWindriderChampion, fioraVictoriousChampion, karmaChannelerChampion, karthusEternalChampion, leonaDeterminedChampion, settKingpinChampion, shenKinkouChampion, dariusExecutionerChampion, viktorLeaderChampion } from "./champions.js";
export { blazingScorcherUnit, brazenBuccaneerUnit, flameChompersUnit, legionRearguardUnit, magmaWurmUnit, noxusHopefulUnit, poutyPoroUnit, captainFarronUnit, dangerousDuoUnit, ragingSoulUnit, scrapyardChampionUnit, brynhirThundersongUnit, ragingFirebrandUnit, immortalPhoenixUnit, kadregrinTheInfernalUnit } from "./units-fury.js";
export { clockworkKeeperUnit, playfulPhantomUnit, solariShieldbearerUnit, stalwartPoroUnit, sunlitGuardianUnit, wielderOfWaterUnit, adaptatronUnit, eclipseHeraldUnit, poroHerderUnit, wizenedElderUnit, mageseekerWardenUnit, tastyFaefolkUnit, whiteflameProtectorUnit } from "./units-calm.js";
export { jeweledColossusUnit, lecturingYordleUnit, megaMechUnit, pitCrewUnit, riptideRexUnit, watchfulSentryUnit, blastconeFaeUnit, gemcraftSeerUnit, ravenbloomStudentUnit, spriteMotherUnit, avaAchieverUnit, thousandTailedWatcherUnit, wraithOfEchoesUnit } from "./units-mind.js";
export { crackshotCorsairUnit, duneDrakeUnit, firstMateUnit, pakaaCubUnit, pitRookieUnit, stormclawUrsineUnit, cithriaOfCloudfieldUnit, heraldOfScalesUnit, kinkouMonkUnit, mountainDrakeUnit, wildclawShamanUnit, carnivorousSnapvineUnit, krakenHunterUnit, deadbloomPredatorUnit } from "./units-body.js";
export { cemeteryAttendantUnit, emberMonkUnit, mysticPoroUnit, saiScoutUnit, shipyardSkulkerUnit, sneakyDeckhandUnit, stealthyPursuerUnit, undercoverAgentUnit, travelingMerchantUnit, zauniteBouncerUnit, maddenedMarauderUnit, mindsplitterUnit, rhasaTheSundererUnit, soulgorgerUnit, tideturnerUnit } from "./units-chaos.js";
export { cruelPatronUnit, daringPoroUnit, faithfulManufactorUnit, pettyOfficerUnit, soaringScoutUnit, trifarianGloryseekerUnit, vanguardSergeantUnit, noxianDrummerUnit, peakGuardianUnit, solariChiefUnit, spectralMatronUnit, albusFerrosUnit, commanderLedrosUnit, harnessedDragonUnit, machineEvangelUnit } from "./units-order.js";
export { cleaveSpell, disintegrateSpell, hextechRaySpell, skySplitterSpell, thermoBeamSpell, voidSeekerSpell, blindFurySpell, fallingStarSpell, shakedownSpell, charmSpell, enGardeSpell, findYourCenterSpell, meditationSpell, runePrisonSpell, standUnitedSpell, blockSpell, disciplineSpell, reinforceSpell, windWallSpell, lastStandSpell, partyFavorsSpell, mysticReversalSpell, consultThePastSpell, fallingCometSpell, smokeScreenSpell, spriteCallSpell, stupefySpell, portalRescueSpell, retreatSpell, singularitySpell, convergentMutationSpell, progressDaySpell, promisingFutureSpell, timeWarpSpell, uncheckedPowerSpell, cannonBarrageSpell, challengeSpell, confrontSpell, flurryOfBladesSpell, mobilizeSpell, catalystOfAeonsSpell, spoilsOfWarSpell, unyieldingSpiritSpell, wallopSpell, overtOperationSpell, primalStrengthSpell, sabotageSpell, fightOrFlightSpell, gustSpell, morbidReturnSpell, rebukeSpell, rideTheWindSpell, acceptableLossesSpell, fadingMemoriesSpell, stackedDeckSpell, whirlwindSpell, theHarrowingSpell, invertTimelinesSpell, possessionSpell, backToBackSpell, callToGlorySpell, cullTheWeakSpell, hiddenBladeSpell, facebreakerSpell, imperialDecreeSpell, salvageSpell, vengeanceSpell, grandStrategemSpell, kingsEdictSpell, divineJudgmentSpell, icathianRainSpell, stormbringerSpell, superMegaDeathRocketSpell, noxianGuillotineSpell, foxFireSpell, dragonsRageSpell, lastBreathSpell, zenithBladeSpell, guerillaWarfareSpell, siphonPowerSpell, bulletTimeSpell, showstopperSpell } from "./spells.js";
export { sunDiscGear, unlicensedArmoryGear, ravenbornTomeGear, sealOfRageGear, maskOfForesightGear, spiritsRefugeGear, solariShrineGear, zhonyasHourglassGear, sealOfFocusGear, orbOfRegretGear, energyConduitGear, garbageGrabberGear, mushroomPouchGear, sealOfInsightGear, arenaBarGear, piratesHavenGear, mistfallGear, dazzlingAuroraGear, sealOfStrengthGear, packOfWondersGear, scrapheapGear, theSyrenGear, treasureTroveGear, sealOfDiscordGear, forgeOfTheFutureGear, symbolOfTheSolariGear, vanguardHelmGear, baitedHookGear, sealOfUnityGear } from "./gear.js";
export { altarToUnityBattlefield, aspirantsClimbBattlefield, backAlleyBarBattlefield, bandleTreeBattlefield, fortifiedPositionBattlefield, groveOfTheGodWillowBattlefield, hallowedTombBattlefield, monasteryOfHiranaBattlefield, novariFightingPitBattlefield, obeliskOfPowerBattlefield, reaversRowBattlefield, reckonersArenaBattlefield, sigilOfTheStormBattlefield, startippedPeakBattlefield, targonsPeakBattlefield, theArenasGreatestBattlefield, theCandlelitSanctumBattlefield, theDreamingTreeBattlefield, trifarianWarCampBattlefield, vilemawsLairBattlefield, voidGateBattlefield, windsweptHillockBattlefield } from "./battlefields.js";
export { recruitToken, recruitToken272, recruitToken273, spriteToken } from "./tokens.js";

import { kaisaDaughterOfTheVoidLegend, volibearRelentlessStormLegend, dariusHandOfNoxusLegend, ahriNineTailedFoxLegend, yasuoUnforgivenLegend, leonaRadiantDawnLegend, teemoSwiftScoutLegend, missFortuneBountyHunterLegend, settTheBossLegend } from "./legends.js";
import { dariusTrifarianChampion, dravenShowboatChampion, tryndamereBarbarianChampion, vayneHunterChampion, viDestructiveChampion, kaisaSurvivorChampion, volibearFuriousChampion, ahriAlluringChampion, blitzcrankImpassiveChampion, sonaHarmoniousChampion, taricProtectorChampion, yasuoRemorsefulChampion, leeSinAsceticChampion, leonaZealotChampion, drMundoExpertChampion, ekkoRecurrentChampion, heimerdingerInventorChampion, kaisaEvolutionaryChampion, malzaharFanaticChampion, viktorInnovatorChampion, ahriInquisitiveChampion, teemoStrategistChampion, aniviaPrimalChampion, leeSinCenteredChampion, qiyanaVictoriousChampion, udyrWildmanChampion, volibearImposingChampion, warwickHunterChampion, missFortuneCaptainChampion, settBrawlerChampion, kaynUnleashedChampion, kogmawCausticChampion, missFortuneBuccaneerChampion, nocturneHorrifyingChampion, teemoScoutChampion, twistedFateGamblerChampion, jinxRebelChampion, yasuoWindriderChampion, fioraVictoriousChampion, karmaChannelerChampion, karthusEternalChampion, leonaDeterminedChampion, settKingpinChampion, shenKinkouChampion, dariusExecutionerChampion, viktorLeaderChampion } from "./champions.js";
import { blazingScorcherUnit, brazenBuccaneerUnit, flameChompersUnit, legionRearguardUnit, magmaWurmUnit, noxusHopefulUnit, poutyPoroUnit, captainFarronUnit, dangerousDuoUnit, ragingSoulUnit, scrapyardChampionUnit, brynhirThundersongUnit, ragingFirebrandUnit, immortalPhoenixUnit, kadregrinTheInfernalUnit } from "./units-fury.js";
import { clockworkKeeperUnit, playfulPhantomUnit, solariShieldbearerUnit, stalwartPoroUnit, sunlitGuardianUnit, wielderOfWaterUnit, adaptatronUnit, eclipseHeraldUnit, poroHerderUnit, wizenedElderUnit, mageseekerWardenUnit, tastyFaefolkUnit, whiteflameProtectorUnit } from "./units-calm.js";
import { jeweledColossusUnit, lecturingYordleUnit, megaMechUnit, pitCrewUnit, riptideRexUnit, watchfulSentryUnit, blastconeFaeUnit, gemcraftSeerUnit, ravenbloomStudentUnit, spriteMotherUnit, avaAchieverUnit, thousandTailedWatcherUnit, wraithOfEchoesUnit } from "./units-mind.js";
import { crackshotCorsairUnit, duneDrakeUnit, firstMateUnit, pakaaCubUnit, pitRookieUnit, stormclawUrsineUnit, cithriaOfCloudfieldUnit, heraldOfScalesUnit, kinkouMonkUnit, mountainDrakeUnit, wildclawShamanUnit, carnivorousSnapvineUnit, krakenHunterUnit, deadbloomPredatorUnit } from "./units-body.js";
import { cemeteryAttendantUnit, emberMonkUnit, mysticPoroUnit, saiScoutUnit, shipyardSkulkerUnit, sneakyDeckhandUnit, stealthyPursuerUnit, undercoverAgentUnit, travelingMerchantUnit, zauniteBouncerUnit, maddenedMarauderUnit, mindsplitterUnit, rhasaTheSundererUnit, soulgorgerUnit, tideturnerUnit } from "./units-chaos.js";
import { cruelPatronUnit, daringPoroUnit, faithfulManufactorUnit, pettyOfficerUnit, soaringScoutUnit, trifarianGloryseekerUnit, vanguardSergeantUnit, noxianDrummerUnit, peakGuardianUnit, solariChiefUnit, spectralMatronUnit, albusFerrosUnit, commanderLedrosUnit, harnessedDragonUnit, machineEvangelUnit } from "./units-order.js";
import { cleaveSpell, disintegrateSpell, hextechRaySpell, skySplitterSpell, thermoBeamSpell, voidSeekerSpell, blindFurySpell, fallingStarSpell, shakedownSpell, charmSpell, enGardeSpell, findYourCenterSpell, meditationSpell, runePrisonSpell, standUnitedSpell, blockSpell, disciplineSpell, reinforceSpell, windWallSpell, lastStandSpell, partyFavorsSpell, mysticReversalSpell, consultThePastSpell, fallingCometSpell, smokeScreenSpell, spriteCallSpell, stupefySpell, portalRescueSpell, retreatSpell, singularitySpell, convergentMutationSpell, progressDaySpell, promisingFutureSpell, timeWarpSpell, uncheckedPowerSpell, cannonBarrageSpell, challengeSpell, confrontSpell, flurryOfBladesSpell, mobilizeSpell, catalystOfAeonsSpell, spoilsOfWarSpell, unyieldingSpiritSpell, wallopSpell, overtOperationSpell, primalStrengthSpell, sabotageSpell, fightOrFlightSpell, gustSpell, morbidReturnSpell, rebukeSpell, rideTheWindSpell, acceptableLossesSpell, fadingMemoriesSpell, stackedDeckSpell, whirlwindSpell, theHarrowingSpell, invertTimelinesSpell, possessionSpell, backToBackSpell, callToGlorySpell, cullTheWeakSpell, hiddenBladeSpell, facebreakerSpell, imperialDecreeSpell, salvageSpell, vengeanceSpell, grandStrategemSpell, kingsEdictSpell, divineJudgmentSpell, icathianRainSpell, stormbringerSpell, superMegaDeathRocketSpell, noxianGuillotineSpell, foxFireSpell, dragonsRageSpell, lastBreathSpell, zenithBladeSpell, guerillaWarfareSpell, siphonPowerSpell, bulletTimeSpell, showstopperSpell } from "./spells.js";
import { sunDiscGear, unlicensedArmoryGear, ravenbornTomeGear, sealOfRageGear, maskOfForesightGear, spiritsRefugeGear, solariShrineGear, zhonyasHourglassGear, sealOfFocusGear, orbOfRegretGear, energyConduitGear, garbageGrabberGear, mushroomPouchGear, sealOfInsightGear, arenaBarGear, piratesHavenGear, mistfallGear, dazzlingAuroraGear, sealOfStrengthGear, packOfWondersGear, scrapheapGear, theSyrenGear, treasureTroveGear, sealOfDiscordGear, forgeOfTheFutureGear, symbolOfTheSolariGear, vanguardHelmGear, baitedHookGear, sealOfUnityGear } from "./gear.js";
import { altarToUnityBattlefield, aspirantsClimbBattlefield, backAlleyBarBattlefield, bandleTreeBattlefield, fortifiedPositionBattlefield, groveOfTheGodWillowBattlefield, hallowedTombBattlefield, monasteryOfHiranaBattlefield, novariFightingPitBattlefield, obeliskOfPowerBattlefield, reaversRowBattlefield, reckonersArenaBattlefield, sigilOfTheStormBattlefield, startippedPeakBattlefield, targonsPeakBattlefield, theArenasGreatestBattlefield, theCandlelitSanctumBattlefield, theDreamingTreeBattlefield, trifarianWarCampBattlefield, vilemawsLairBattlefield, voidGateBattlefield, windsweptHillockBattlefield } from "./battlefields.js";
import { recruitToken, recruitToken272, recruitToken273, spriteToken } from "./tokens.js";

export const originsAllCards: CardDefinition[] = [
  ...sampleCards,
  kaisaDaughterOfTheVoidLegend,
  volibearRelentlessStormLegend,
  dariusHandOfNoxusLegend,
  ahriNineTailedFoxLegend,
  yasuoUnforgivenLegend,
  leonaRadiantDawnLegend,
  teemoSwiftScoutLegend,
  missFortuneBountyHunterLegend,
  settTheBossLegend,
  dariusTrifarianChampion,
  dravenShowboatChampion,
  tryndamereBarbarianChampion,
  vayneHunterChampion,
  viDestructiveChampion,
  kaisaSurvivorChampion,
  volibearFuriousChampion,
  ahriAlluringChampion,
  blitzcrankImpassiveChampion,
  sonaHarmoniousChampion,
  taricProtectorChampion,
  yasuoRemorsefulChampion,
  leeSinAsceticChampion,
  leonaZealotChampion,
  drMundoExpertChampion,
  ekkoRecurrentChampion,
  heimerdingerInventorChampion,
  kaisaEvolutionaryChampion,
  malzaharFanaticChampion,
  viktorInnovatorChampion,
  ahriInquisitiveChampion,
  teemoStrategistChampion,
  aniviaPrimalChampion,
  leeSinCenteredChampion,
  qiyanaVictoriousChampion,
  udyrWildmanChampion,
  volibearImposingChampion,
  warwickHunterChampion,
  missFortuneCaptainChampion,
  settBrawlerChampion,
  kaynUnleashedChampion,
  kogmawCausticChampion,
  missFortuneBuccaneerChampion,
  nocturneHorrifyingChampion,
  teemoScoutChampion,
  twistedFateGamblerChampion,
  jinxRebelChampion,
  yasuoWindriderChampion,
  fioraVictoriousChampion,
  karmaChannelerChampion,
  karthusEternalChampion,
  leonaDeterminedChampion,
  settKingpinChampion,
  shenKinkouChampion,
  dariusExecutionerChampion,
  viktorLeaderChampion,
  blazingScorcherUnit,
  brazenBuccaneerUnit,
  flameChompersUnit,
  legionRearguardUnit,
  magmaWurmUnit,
  noxusHopefulUnit,
  poutyPoroUnit,
  captainFarronUnit,
  dangerousDuoUnit,
  ragingSoulUnit,
  scrapyardChampionUnit,
  brynhirThundersongUnit,
  ragingFirebrandUnit,
  immortalPhoenixUnit,
  kadregrinTheInfernalUnit,
  clockworkKeeperUnit,
  playfulPhantomUnit,
  solariShieldbearerUnit,
  stalwartPoroUnit,
  sunlitGuardianUnit,
  wielderOfWaterUnit,
  adaptatronUnit,
  eclipseHeraldUnit,
  poroHerderUnit,
  wizenedElderUnit,
  mageseekerWardenUnit,
  tastyFaefolkUnit,
  whiteflameProtectorUnit,
  jeweledColossusUnit,
  lecturingYordleUnit,
  megaMechUnit,
  pitCrewUnit,
  riptideRexUnit,
  watchfulSentryUnit,
  blastconeFaeUnit,
  gemcraftSeerUnit,
  ravenbloomStudentUnit,
  spriteMotherUnit,
  avaAchieverUnit,
  thousandTailedWatcherUnit,
  wraithOfEchoesUnit,
  crackshotCorsairUnit,
  duneDrakeUnit,
  firstMateUnit,
  pakaaCubUnit,
  pitRookieUnit,
  stormclawUrsineUnit,
  cithriaOfCloudfieldUnit,
  heraldOfScalesUnit,
  kinkouMonkUnit,
  mountainDrakeUnit,
  wildclawShamanUnit,
  carnivorousSnapvineUnit,
  krakenHunterUnit,
  deadbloomPredatorUnit,
  cemeteryAttendantUnit,
  emberMonkUnit,
  mysticPoroUnit,
  saiScoutUnit,
  shipyardSkulkerUnit,
  sneakyDeckhandUnit,
  stealthyPursuerUnit,
  undercoverAgentUnit,
  travelingMerchantUnit,
  zauniteBouncerUnit,
  maddenedMarauderUnit,
  mindsplitterUnit,
  rhasaTheSundererUnit,
  soulgorgerUnit,
  tideturnerUnit,
  cruelPatronUnit,
  daringPoroUnit,
  faithfulManufactorUnit,
  pettyOfficerUnit,
  soaringScoutUnit,
  trifarianGloryseekerUnit,
  vanguardSergeantUnit,
  noxianDrummerUnit,
  peakGuardianUnit,
  solariChiefUnit,
  spectralMatronUnit,
  albusFerrosUnit,
  commanderLedrosUnit,
  harnessedDragonUnit,
  machineEvangelUnit,
  cleaveSpell,
  disintegrateSpell,
  hextechRaySpell,
  skySplitterSpell,
  thermoBeamSpell,
  voidSeekerSpell,
  blindFurySpell,
  fallingStarSpell,
  shakedownSpell,
  charmSpell,
  enGardeSpell,
  findYourCenterSpell,
  meditationSpell,
  runePrisonSpell,
  standUnitedSpell,
  blockSpell,
  disciplineSpell,
  reinforceSpell,
  windWallSpell,
  lastStandSpell,
  partyFavorsSpell,
  mysticReversalSpell,
  consultThePastSpell,
  fallingCometSpell,
  smokeScreenSpell,
  spriteCallSpell,
  stupefySpell,
  portalRescueSpell,
  retreatSpell,
  singularitySpell,
  convergentMutationSpell,
  progressDaySpell,
  promisingFutureSpell,
  timeWarpSpell,
  uncheckedPowerSpell,
  cannonBarrageSpell,
  challengeSpell,
  confrontSpell,
  flurryOfBladesSpell,
  mobilizeSpell,
  catalystOfAeonsSpell,
  spoilsOfWarSpell,
  unyieldingSpiritSpell,
  wallopSpell,
  overtOperationSpell,
  primalStrengthSpell,
  sabotageSpell,
  fightOrFlightSpell,
  gustSpell,
  morbidReturnSpell,
  rebukeSpell,
  rideTheWindSpell,
  acceptableLossesSpell,
  fadingMemoriesSpell,
  stackedDeckSpell,
  whirlwindSpell,
  theHarrowingSpell,
  invertTimelinesSpell,
  possessionSpell,
  backToBackSpell,
  callToGlorySpell,
  cullTheWeakSpell,
  hiddenBladeSpell,
  facebreakerSpell,
  imperialDecreeSpell,
  salvageSpell,
  vengeanceSpell,
  grandStrategemSpell,
  kingsEdictSpell,
  divineJudgmentSpell,
  icathianRainSpell,
  stormbringerSpell,
  superMegaDeathRocketSpell,
  noxianGuillotineSpell,
  foxFireSpell,
  dragonsRageSpell,
  lastBreathSpell,
  zenithBladeSpell,
  guerillaWarfareSpell,
  siphonPowerSpell,
  bulletTimeSpell,
  showstopperSpell,
  sunDiscGear,
  unlicensedArmoryGear,
  ravenbornTomeGear,
  sealOfRageGear,
  maskOfForesightGear,
  spiritsRefugeGear,
  solariShrineGear,
  zhonyasHourglassGear,
  sealOfFocusGear,
  orbOfRegretGear,
  energyConduitGear,
  garbageGrabberGear,
  mushroomPouchGear,
  sealOfInsightGear,
  arenaBarGear,
  piratesHavenGear,
  mistfallGear,
  dazzlingAuroraGear,
  sealOfStrengthGear,
  packOfWondersGear,
  scrapheapGear,
  theSyrenGear,
  treasureTroveGear,
  sealOfDiscordGear,
  forgeOfTheFutureGear,
  symbolOfTheSolariGear,
  vanguardHelmGear,
  baitedHookGear,
  sealOfUnityGear,
  altarToUnityBattlefield,
  aspirantsClimbBattlefield,
  backAlleyBarBattlefield,
  bandleTreeBattlefield,
  fortifiedPositionBattlefield,
  groveOfTheGodWillowBattlefield,
  hallowedTombBattlefield,
  monasteryOfHiranaBattlefield,
  novariFightingPitBattlefield,
  obeliskOfPowerBattlefield,
  reaversRowBattlefield,
  reckonersArenaBattlefield,
  sigilOfTheStormBattlefield,
  startippedPeakBattlefield,
  targonsPeakBattlefield,
  theArenasGreatestBattlefield,
  theCandlelitSanctumBattlefield,
  theDreamingTreeBattlefield,
  trifarianWarCampBattlefield,
  vilemawsLairBattlefield,
  voidGateBattlefield,
  windsweptHillockBattlefield,
  recruitToken,
  recruitToken272,
  recruitToken273,
  spriteToken,
];

/** @deprecated Use originsAllCards instead */
export const originsCards = originsAllCards;
